<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            // ========== Laptop Gaming ==========
            [
                'product_id' => 'L001',
                'product_name' => 'ASUS ROG Strix G16',
                'product_image' => 'rog_strix_g16.jpg',
                'product_cost' => 35000000.00,
                'product_price' => 39990000.00,
                'discount' => 10.00,
                'description' => 'Laptop gaming cao cấp với CPU Intel Gen 13 và GPU RTX 4070',
                'category' => 'Laptop Gaming',
                'rating' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 'L002',
                'product_name' => 'MSI Katana 15',
                'product_image' => 'msi_katana_15.jpg',
                'product_cost' => 28000000.00,
                'product_price' => 31990000.00,
                'discount' => 8.00,
                'description' => 'Thiết kế mạnh mẽ, phù hợp cho game thủ với RTX 4060',
                'category' => 'Laptop Gaming',
                'rating' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 'L003',
                'product_name' => 'Acer Nitro 5',
                'product_image' => 'acer_nitro_5.jpg',
                'product_cost' => 22000000.00,
                'product_price' => 24990000.00,
                'discount' => 12.00,
                'description' => 'Laptop gaming phổ thông, hiệu năng ổn định với RTX 3050 Ti',
                'category' => 'Laptop Gaming',
                'rating' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 'L004',
                'product_name' => 'Lenovo Legion 5 Pro',
                'product_image' => 'lenovo_legion_5pro.jpg',
                'product_cost' => 33000000.00,
                'product_price' => 37990000.00,
                'discount' => 7.00,
                'description' => 'Màn hình 16 inch QHD+, tối ưu cho game và đồ họa',
                'category' => 'Laptop Gaming',
                'rating' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ========== Điện thoại ==========
            [
                'product_id' => 'P001',
                'product_name' => 'iPhone 15 Pro Max',
                'product_image' => 'iphone_15_pro_max.jpg',
                'product_cost' => 29000000.00,
                'product_price' => 32990000.00,
                'discount' => 5.00,
                'description' => 'Điện thoại cao cấp của Apple với chip A17 Pro, màn hình 120Hz',
                'category' => 'Điện thoại',
                'rating' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 'P002',
                'product_name' => 'Samsung Galaxy S23 Ultra',
                'product_image' => 's23_ultra.jpg',
                'product_cost' => 26000000.00,
                'product_price' => 28990000.00,
                'discount' => 8.00,
                'description' => 'Flagship Samsung với camera 200MP, Snapdragon 8 Gen 2',
                'category' => 'Điện thoại',
                'rating' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 'P003',
                'product_name' => 'Xiaomi 13T Pro',
                'product_image' => 'xiaomi_13t_pro.jpg',
                'product_cost' => 16000000.00,
                'product_price' => 17990000.00,
                'discount' => 10.00,
                'description' => 'Điện thoại hiệu năng cao, camera Leica, giá dễ tiếp cận',
                'category' => 'Điện thoại',
                'rating' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 'P004',
                'product_name' => 'Oppo Find X6 Pro',
                'product_image' => 'oppo_find_x6_pro.jpg',
                'product_cost' => 20000000.00,
                'product_price' => 22990000.00,
                'discount' => 9.00,
                'description' => 'Thiết kế sang trọng, camera hợp tác cùng Hasselblad',
                'category' => 'Điện thoại',
                'rating' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ========== Tai nghe ==========
            [
                'product_id' => 'H001',
                'product_name' => 'Sony WH-1000XM5',
                'product_image' => 'sony_wh1000xm5.jpg',
                'product_cost' => 8000000.00,
                'product_price' => 8990000.00,
                'discount' => 6.00,
                'description' => 'Tai nghe chống ồn hàng đầu với âm thanh Hi-Res và pin 30 giờ',
                'category' => 'Tai nghe',
                'rating' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 'H002',
                'product_name' => 'Apple AirPods Pro 2',
                'product_image' => 'airpods_pro_2.jpg',
                'product_cost' => 5500000.00,
                'product_price' => 6290000.00,
                'discount' => 0.00,
                'description' => 'Tai nghe không dây cao cấp với Adaptive Transparency',
                'category' => 'Tai nghe',
                'rating' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 'H003',
                'product_name' => 'Razer BlackShark V2 Pro',
                'product_image' => 'razer_blackshark_v2_pro.jpg',
                'product_cost' => 4500000.00,
                'product_price' => 4990000.00,
                'discount' => 8.00,
                'description' => 'Tai nghe gaming không dây với micro siêu chuẩn',
                'category' => 'Tai nghe',
                'rating' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 'H004',
                'product_name' => 'Bose QuietComfort 45',
                'product_image' => 'bose_qc45.jpg',
                'product_cost' => 7200000.00,
                'product_price' => 7990000.00,
                'discount' => 10.00,
                'description' => 'Tai nghe chống ồn êm ái, pin 24 giờ, chất âm tự nhiên',
                'category' => 'Tai nghe',
                'rating' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ========== Màn hình ==========
            [
                'product_id' => 'M001',
                'product_name' => 'Samsung Odyssey G7',
                'product_image' => 'samsung_odyssey_g7.jpg',
                'product_cost' => 12000000.00,
                'product_price' => 13990000.00,
                'discount' => 15.00,
                'description' => 'Màn hình cong 32 inch QHD 240Hz, hỗ trợ G-Sync và FreeSync',
                'category' => 'Màn hình',
                'rating' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 'M002',
                'product_name' => 'LG UltraGear 27GN950',
                'product_image' => 'lg_ultragear_27gn950.jpg',
                'product_cost' => 16000000.00,
                'product_price' => 17990000.00,
                'discount' => 10.00,
                'description' => 'Màn hình 4K Nano IPS 27 inch, 144Hz, HDR600',
                'category' => 'Màn hình',
                'rating' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 'M003',
                'product_name' => 'AOC CQ32G2',
                'product_image' => 'aoc_cq32g2.jpg',
                'product_cost' => 8500000.00,
                'product_price' => 9990000.00,
                'discount' => 7.00,
                'description' => 'Màn hình cong 32 inch QHD, tần số quét 165Hz',
                'category' => 'Màn hình',
                'rating' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 'M004',
                'product_name' => 'Dell Alienware AW3423DW',
                'product_image' => 'alienware_aw3423dw.jpg',
                'product_cost' => 25000000.00,
                'product_price' => 28990000.00,
                'discount' => 0.00,
                'description' => 'Màn hình cong QD-OLED 34 inch, 175Hz, hỗ trợ HDR',
                'category' => 'Màn hình',
                'rating' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
